import { describe, it, expect } from 'vitest';
import { exportCSSVariables, tokenPathToVariable, groupTokensByType } from '../css';
import { mergeTokens } from '../../merger';

function makeTokens(overrides: Record<string, string | number | boolean> = {}) {
  return mergeTokens({}, overrides, { applyDefaults: true }).tokens;
}

describe('tokenPathToVariable', () => {
  it('converts simple path', () => {
    expect(tokenPathToVariable('color.primary')).toBe('--color-primary');
  });

  it('converts nested path', () => {
    expect(tokenPathToVariable('color.primary.hover')).toBe('--color-primary-hover');
  });

  it('converts font path', () => {
    expect(tokenPathToVariable('font.heading')).toBe('--font-heading');
  });

  it('converts radius path', () => {
    expect(tokenPathToVariable('radius.md')).toBe('--radius-md');
  });
});

describe('groupTokensByType', () => {
  it('groups tokens into correct categories', () => {
    const tokens = makeTokens();
    const groups = groupTokensByType(tokens);

    expect(groups.colors.length).toBeGreaterThan(0);
    expect(groups.radius.length).toBeGreaterThan(0);
    expect(groups.fonts.length).toBeGreaterThan(0);
    expect(groups.spacing.length).toBeGreaterThan(0);
    expect(groups.shadows.length).toBeGreaterThan(0);
  });

  it('sorts variables alphabetically within groups', () => {
    const tokens = makeTokens();
    const groups = groupTokensByType(tokens);

    for (const group of Object.values(groups)) {
      for (let i = 1; i < group.length; i++) {
        expect(group[i].variable >= group[i - 1].variable).toBe(true);
      }
    }
  });
});

describe('exportCSSVariables', () => {
  it('generates :root scope with all variables', () => {
    const tokens = makeTokens();
    const { content } = exportCSSVariables(tokens);

    expect(content).toContain(':root {');
    expect(content).toContain('--color-primary');
    expect(content).toContain('--font-heading');
    expect(content).toContain('--radius-md');
  });

  it('generates scoped class when slug provided', () => {
    const tokens = makeTokens();
    const { content } = exportCSSVariables(tokens, { stylePackSlug: 'saas-clean-v1' });

    expect(content).toContain('.theme-saas-clean-v1 {');
  });

  it('returns correct filename with slug', () => {
    const tokens = makeTokens();
    const { filename } = exportCSSVariables(tokens, { stylePackSlug: 'saas-clean-v1' });

    expect(filename).toBe('saas-clean-v1-tokens.css');
  });

  it('returns default filename without slug', () => {
    const tokens = makeTokens();
    const { filename } = exportCSSVariables(tokens);

    expect(filename).toBe('design-tokens.css');
  });

  it('omits :root when includeRoot is false', () => {
    const tokens = makeTokens();
    const { content } = exportCSSVariables(tokens, {
      includeRoot: false,
      stylePackSlug: 'test',
    });

    expect(content).not.toContain(':root {');
    expect(content).toContain('.theme-test {');
  });

  it('omits scoped class when includeScoped is false', () => {
    const tokens = makeTokens();
    const { content } = exportCSSVariables(tokens, {
      stylePackSlug: 'test',
      includeScoped: false,
    });

    expect(content).toContain(':root {');
    expect(content).not.toContain('.theme-test {');
  });

  it('handles empty token map', () => {
    const tokens = mergeTokens({}, {}, { applyDefaults: false }).tokens;
    const { content } = exportCSSVariables(tokens);

    expect(content).toContain('Auto-generated by AIUI');
  });

  it('includes section comments', () => {
    const tokens = makeTokens();
    const { content } = exportCSSVariables(tokens);

    expect(content).toContain('/* Colors */');
    expect(content).toContain('/* Typography */');
    expect(content).toContain('/* Border Radius */');
  });
});
