import { describe, it, expect } from 'vitest';
import { exportTailwindConfig } from '../tailwind';
import { mergeTokens } from '../../merger';

function makeTokens(overrides: Record<string, string | number | boolean> = {}) {
  return mergeTokens({}, overrides, { applyDefaults: true }).tokens;
}

describe('exportTailwindConfig', () => {
  it('generates valid TypeScript config', () => {
    const tokens = makeTokens();
    const { content, filename } = exportTailwindConfig(tokens);

    expect(filename).toBe('tailwind.config.ts');
    expect(content).toContain("import type { Config } from 'tailwindcss'");
    expect(content).toContain('export default config');
  });

  it('maps color tokens to CSS variable references', () => {
    const tokens = makeTokens({ 'color.primary': '#2563eb' });
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain("'primary': 'var(--color-primary)'");
  });

  it('maps radius tokens to pixel values', () => {
    const tokens = makeTokens({ 'radius.sm': '4px' });
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain("'sm': '4px'");
  });

  it('maps font tokens to font family arrays', () => {
    const tokens = makeTokens({ 'font.heading': 'Inter' });
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain("'heading': ['Inter', 'sans-serif']");
  });

  it('maps spacing tokens', () => {
    const tokens = makeTokens({ 'spacing.unit': '4px' });
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain("'unit': '4px'");
  });

  it('maps shadow tokens', () => {
    const tokens = makeTokens();
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain('boxShadow');
  });

  it('handles empty token namespaces', () => {
    const tokens = mergeTokens({}, {}, { applyDefaults: false }).tokens;
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain('colors: {}');
  });

  it('includes auto-generated header', () => {
    const tokens = makeTokens();
    const { content } = exportTailwindConfig(tokens);

    expect(content).toContain('Auto-generated by AIUI');
  });
});
