import * as cdk from 'aws-cdk-lib';
import * as ec2 from 'aws-cdk-lib/aws-ec2';
import * as rds from 'aws-cdk-lib/aws-rds';
import * as secretsmanager from 'aws-cdk-lib/aws-secretsmanager';
import { Construct } from 'constructs';

export interface RdsStackProps extends cdk.StackProps {
  vpc: ec2.IVpc;
  stage: string;
}

export class RdsStack extends cdk.Stack {
  public readonly dbSecret: secretsmanager.ISecret;
  public readonly dbInstance: rds.DatabaseInstance;
  public readonly dbSecurityGroup: ec2.ISecurityGroup;

  constructor(scope: Construct, id: string, props: RdsStackProps) {
    super(scope, id, props);

    const { vpc, stage } = props;

    // Security group allowing port 5432 from within the VPC
    const dbSecurityGroup = new ec2.SecurityGroup(this, 'DbSecurityGroup', {
      vpc,
      securityGroupName: `aiui-rds-sg-${stage}`,
      description: 'Security group for AIUI RDS PostgreSQL instance',
      allowAllOutbound: true,
    });

    dbSecurityGroup.addIngressRule(
      ec2.Peer.ipv4(vpc.vpcCidrBlock),
      ec2.Port.tcp(5432),
      'Allow PostgreSQL access from within VPC'
    );

    this.dbSecurityGroup = dbSecurityGroup;

    // Determine instance class based on stage
    const instanceType =
      stage === 'prod'
        ? ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.SMALL)
        : ec2.InstanceType.of(ec2.InstanceClass.T3, ec2.InstanceSize.MICRO);

    // RDS PostgreSQL instance with auto-generated Secrets Manager credentials
    this.dbInstance = new rds.DatabaseInstance(this, 'AiuiDatabase', {
      instanceIdentifier: `aiui-db-${stage}`,
      engine: rds.DatabaseInstanceEngine.postgres({
        version: rds.PostgresEngineVersion.VER_15,
      }),
      instanceType,
      vpc,
      vpcSubnets: {
        subnetType:
          stage === 'prod' ? ec2.SubnetType.PRIVATE_WITH_EGRESS : ec2.SubnetType.PRIVATE_ISOLATED,
      },
      securityGroups: [dbSecurityGroup],
      databaseName: 'aiui',
      credentials: rds.Credentials.fromGeneratedSecret('aiui_admin', {
        secretName: `aiui/rds-credentials/${stage}`,
      }),
      allocatedStorage: 20,
      maxAllocatedStorage: 100,
      storageType: rds.StorageType.GP3,
      multiAz: stage === 'prod',
      backupRetention: cdk.Duration.days(7),
      deletionProtection: stage === 'prod',
      removalPolicy: stage === 'prod' ? cdk.RemovalPolicy.RETAIN : cdk.RemovalPolicy.DESTROY,
      publiclyAccessible: false,
    });

    // The secret is auto-generated by Credentials.fromGeneratedSecret
    this.dbSecret = this.dbInstance.secret!;

    // Outputs
    new cdk.CfnOutput(this, 'DbSecretArn', {
      value: this.dbSecret.secretArn,
      description: 'ARN of the Secrets Manager secret containing DB credentials',
    });

    new cdk.CfnOutput(this, 'DbEndpoint', {
      value: this.dbInstance.dbInstanceEndpointAddress,
      description: 'RDS instance endpoint address',
    });

    new cdk.CfnOutput(this, 'DbSecurityGroupId', {
      value: dbSecurityGroup.securityGroupId,
      description: 'Security group ID for the RDS instance',
    });
  }
}
