import type { RegistryToken } from './registry-client.js';

type OutputFormat = 'tailwind' | 'css' | 'json' | 'react-native' | 'inline-css';

/**
 * Determine the best output format based on framework detection.
 */
export function inferFormat(framework: string, hasTailwind: boolean): OutputFormat {
  if (framework === 'react-native') return 'react-native';
  if (framework === 'email') return 'inline-css';
  if (hasTailwind) return 'tailwind';
  if (framework === 'nextjs' || framework === 'vite' || framework === 'react') return 'css';
  return 'json';
}

/**
 * Transform tokens into a Tailwind CSS config extend block.
 */
function toTailwindConfig(tokens: RegistryToken[]): string {
  const grouped: Record<string, Record<string, string>> = {};

  for (const token of tokens) {
    const category = mapTokenTypeToTailwind(token.type);
    if (!grouped[category]) grouped[category] = {};
    const key = token.key.replace(`${token.type}-`, '').replace(/[^a-zA-Z0-9-]/g, '-');
    grouped[category][key] = token.value;
  }

  const sections = Object.entries(grouped)
    .map(([category, values]) => {
      const entries = Object.entries(values)
        .map(([k, v]) => `        '${k}': '${v}',`)
        .join('\n');
      return `      ${category}: {\n${entries}\n      },`;
    })
    .join('\n');

  return `// Generated by AIUI CLI — do not edit manually
// Regenerate with: npx @aiui/cli sync

/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
${sections}
    },
  },
};
`;
}

function mapTokenTypeToTailwind(type: string): string {
  const map: Record<string, string> = {
    color: 'colors',
    font: 'fontFamily',
    'font-size': 'fontSize',
    'font-weight': 'fontWeight',
    'line-height': 'lineHeight',
    'letter-spacing': 'letterSpacing',
    spacing: 'spacing',
    radius: 'borderRadius',
    shadow: 'boxShadow',
    elevation: 'zIndex',
    'z-index': 'zIndex',
    opacity: 'opacity',
    'border-width': 'borderWidth',
    breakpoint: 'screens',
    animation: 'animation',
    transition: 'transitionDuration',
  };
  return map[type] ?? type;
}

/**
 * Transform tokens into CSS custom properties.
 */
function toCssVars(tokens: RegistryToken[]): string {
  const lines = tokens.map((t) => `  --${t.key}: ${t.value};`);
  return `/* Generated by AIUI CLI — do not edit manually */
/* Regenerate with: npx @aiui/cli sync */

:root {
${lines.join('\n')}
}
`;
}

/**
 * Transform tokens into a normalized JSON file.
 */
function toJson(tokens: RegistryToken[]): string {
  const obj: Record<string, { value: string; type: string; description?: string }> = {};
  for (const t of tokens) {
    obj[t.key] = { value: t.value, type: t.type };
    if (t.description) obj[t.key].description = t.description;
  }
  return JSON.stringify(obj, null, 2) + '\n';
}

/**
 * Transform tokens into a React Native StyleSheet object.
 */
function toReactNative(tokens: RegistryToken[]): string {
  const obj: Record<string, string> = {};
  for (const t of tokens) {
    const key = t.key.replace(/[^a-zA-Z0-9]/g, '_');
    obj[key] = t.value;
  }
  return `// Generated by AIUI CLI
import { StyleSheet } from 'react-native';

export const tokens = ${JSON.stringify(obj, null, 2)};

export const styles = StyleSheet.create({
  // Add common semantic mappings here
});
`;
}

/**
 * Transform tokens into an inline CSS object for emails.
 */
function toInlineCss(tokens: RegistryToken[]): string {
  const obj: Record<string, string> = {};
  for (const t of tokens) {
    obj[t.key] = t.value;
  }
  return `// Generated by AIUI CLI for React Email
export const designTokens = ${JSON.stringify(obj, null, 2)};
`;
}

/**
 * Transform tokens into the specified output format.
 */
export function transformTokens(
  tokens: RegistryToken[],
  format: OutputFormat
): { content: string; filename: string } {
  switch (format) {
    case 'tailwind':
      return { content: toTailwindConfig(tokens), filename: 'aiui.tailwind.config.ts' };
    case 'css':
      return { content: toCssVars(tokens), filename: 'aiui.tokens.css' };
    case 'react-native':
      return { content: toReactNative(tokens), filename: 'aiui.tokens.rn.ts' };
    case 'inline-css':
      return { content: toInlineCss(tokens), filename: 'aiui.tokens.email.ts' };
    case 'json':
      return { content: toJson(tokens), filename: 'tokens.json' };
  }
}

/**
 * Transform a component recipe by injecting active tokens and resolving imports.
 */
export function transformComponent(
  component: { codeTemplate: string; name: string; slug: string },
  tokens: RegistryToken[],
  format: OutputFormat
): string {
  let code = component.codeTemplate;

  // 1. Simple token substitution if the template uses {{token:key}} syntax
  for (const token of tokens) {
    const placeholder = new RegExp(`{{token:${token.key}}}`, 'g');
    code = code.replace(placeholder, token.value);
  }

  // 2. Format-specific injections
  if (format === 'tailwind') {
    // If the template uses hardcoded classes that we want to override with our tokens,
    // we can do smarter regex replacement here.
    // For now, we assume the templates are written to be compatible with the aiui tailwind config.
  }

  // 3. Add generated header
  const header = `/**
 * Component: ${component.name} (${component.slug})
 * Generated by AIUI CLI
 * Style Pack tokens applied.
 */\n\n`;

  return header + code;
}
