import * as fs from 'node:fs';
import * as path from 'node:path';
import { ensureAiuiDir } from './config.js';
import type { RegistryItem, RegistryToken } from './registry-client.js';

const TOKEN_TYPE_ORDER = [
  'color',
  'font',
  'font-size',
  'font-weight',
  'line-height',
  'letter-spacing',
  'spacing',
  'radius',
  'shadow',
  'elevation',
  'z-index',
  'opacity',
  'border-width',
  'breakpoint',
  'animation',
  'transition',
];

/**
 * Generate design-memory.md markdown from a registry item.
 * Follows the 5-layer structure used by the MCP design-memory tool.
 */
export function generateDesignMemory(pack: RegistryItem): string {
  const lines: string[] = [];

  lines.push(`# Design Memory — ${pack.name}`);
  lines.push('');
  lines.push(`> Auto-generated by AIUI CLI. Regenerate with: \`npx @aiui/cli sync\``);
  lines.push('');
  lines.push(`- **Style Pack:** ${pack.name} (${pack.category})`);
  lines.push(`- **Version:** ${pack.version}`);
  lines.push(`- **Tokens:** ${pack.tokenCount}`);
  lines.push(`- **Components:** ${pack.componentCount}`);
  lines.push(`- **Generated:** ${new Date().toISOString()}`);
  lines.push('');

  // Design rules
  lines.push('## Design Rules');
  lines.push('');
  lines.push('1. **Always use design tokens** — never hardcode colors, spacing, or font values');
  lines.push('2. **Follow the component library** — use provided recipes before creating new ones');
  lines.push(
    '3. **Maintain visual hierarchy** — use heading scale, consistent spacing, proper contrast'
  );
  lines.push('4. **Respect the type system** — use defined font families, sizes, and weights');
  lines.push('5. **Use the spacing scale** — follow spacing tokens for margin, padding, and gap');
  lines.push('6. **Maintain accessibility** — meet WCAG 2.1 AA for contrast and text sizing');
  lines.push('7. **Preserve design consistency** — match the design system across all screens');
  lines.push('');

  // Tokens grouped by type
  lines.push('## Foundation Tokens');
  lines.push('');

  const tokensByType = groupTokensByType(pack.tokens);
  for (const type of TOKEN_TYPE_ORDER) {
    const tokens = tokensByType[type];
    if (!tokens || tokens.length === 0) continue;

    const label = type.charAt(0).toUpperCase() + type.slice(1).replace(/-/g, ' ');
    lines.push(`### ${label}`);
    lines.push('');
    lines.push('| Token | Value |');
    lines.push('|-------|-------|');
    for (const t of tokens) {
      lines.push(`| \`${t.key}\` | \`${t.value}\` |`);
    }
    lines.push('');
  }

  // Components
  if (pack.componentSlugs.length > 0) {
    lines.push('## Component Library');
    lines.push('');
    lines.push('Available components:');
    lines.push('');
    for (const slug of pack.componentSlugs) {
      lines.push(`- \`${slug}\``);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function groupTokensByType(tokens: RegistryToken[]): Record<string, RegistryToken[]> {
  const groups: Record<string, RegistryToken[]> = {};
  for (const token of tokens) {
    if (!groups[token.type]) groups[token.type] = [];
    groups[token.type].push(token);
  }
  return groups;
}

/**
 * Write design-memory.md to .aiui/ directory.
 */
export function writeDesignMemory(pack: RegistryItem, cwd: string = process.cwd()): void {
  const dir = ensureAiuiDir(cwd);
  const md = generateDesignMemory(pack);
  fs.writeFileSync(path.join(dir, 'design-memory.md'), md);
}

/**
 * Write tokens.json to .aiui/ directory.
 */
export function writeTokensJson(tokens: RegistryToken[], cwd: string = process.cwd()): void {
  const dir = ensureAiuiDir(cwd);
  const obj: Record<string, string> = {};
  for (const t of tokens) {
    obj[t.key] = t.value;
  }
  fs.writeFileSync(path.join(dir, 'tokens.json'), JSON.stringify(obj, null, 2) + '\n');
}

/**
 * Add .aiui/tokens.json to .gitignore if not already present.
 */
export function addToGitignore(cwd: string = process.cwd()): void {
  const gitignorePath = path.join(cwd, '.gitignore');
  const entry = '.aiui/tokens.json';

  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf-8');
    if (content.includes(entry)) return;
    fs.appendFileSync(gitignorePath, `\n# AIUI generated tokens\n${entry}\n`);
  }
}
