import * as fs from 'node:fs';
import * as path from 'node:path';
import { ensureAiuiDir } from './config.js';

export interface LocalToken {
  key: string;
  type: string;
  value: string;
  description?: string;
}

const TOKEN_TYPE_ORDER = [
  'color',
  'font',
  'font-size',
  'font-weight',
  'line-height',
  'letter-spacing',
  'spacing',
  'radius',
  'shadow',
  'elevation',
  'z-index',
  'opacity',
  'border-width',
  'breakpoint',
  'animation',
  'transition',
];

/**
 * Generate a project's design-memory.md from a flat token list.
 * After the style-pack/component scope cut, the CLI just writes a
 * tokens-only memory — the canonical design memory still lives on
 * the server (use the MCP `sync_design_memory` tool for the rich version).
 */
export function generateDesignMemory(projectName: string, tokens: LocalToken[]): string {
  const lines: string[] = [];

  lines.push(`# Design Memory — ${projectName}`);
  lines.push('');
  lines.push('> Auto-generated by AIUI CLI. Regenerate with: `aiui sync`');
  lines.push('');
  lines.push(`- **Project:** ${projectName}`);
  lines.push(`- **Tokens:** ${tokens.length}`);
  lines.push(`- **Generated:** ${new Date().toISOString()}`);
  lines.push('');

  lines.push('## Design Rules');
  lines.push('');
  lines.push('1. **Always use design tokens** — never hardcode colors, spacing, or font values');
  lines.push(
    '2. **Maintain visual hierarchy** — use heading scale, consistent spacing, proper contrast'
  );
  lines.push('3. **Respect the type system** — use defined font families, sizes, and weights');
  lines.push('4. **Use the spacing scale** — follow spacing tokens for margin, padding, and gap');
  lines.push('5. **Maintain accessibility** — meet WCAG 2.1 AA for contrast and text sizing');
  lines.push('6. **Preserve design consistency** — match the design system across all screens');
  lines.push('');

  lines.push('## Tokens');
  lines.push('');

  const tokensByType = groupTokensByType(tokens);
  for (const type of TOKEN_TYPE_ORDER) {
    const ofType = tokensByType[type];
    if (!ofType || ofType.length === 0) continue;

    const label = type.charAt(0).toUpperCase() + type.slice(1).replace(/-/g, ' ');
    lines.push(`### ${label}`);
    lines.push('');
    lines.push('| Token | Value |');
    lines.push('|-------|-------|');
    for (const t of ofType) {
      lines.push(`| \`${t.key}\` | \`${t.value}\` |`);
    }
    lines.push('');
  }

  return lines.join('\n');
}

function groupTokensByType(tokens: LocalToken[]): Record<string, LocalToken[]> {
  const groups: Record<string, LocalToken[]> = {};
  for (const token of tokens) {
    if (!groups[token.type]) groups[token.type] = [];
    groups[token.type].push(token);
  }
  return groups;
}

export function writeDesignMemory(
  projectName: string,
  tokens: LocalToken[],
  cwd: string = process.cwd()
): void {
  const dir = ensureAiuiDir(cwd);
  const md = generateDesignMemory(projectName, tokens);
  fs.writeFileSync(path.join(dir, 'design-memory.md'), md);
}

export function writeTokensJson(tokens: LocalToken[], cwd: string = process.cwd()): void {
  const dir = ensureAiuiDir(cwd);
  const obj: Record<string, string> = {};
  for (const t of tokens) {
    obj[t.key] = t.value;
  }
  fs.writeFileSync(path.join(dir, 'tokens.json'), JSON.stringify(obj, null, 2) + '\n');
}

export function addToGitignore(cwd: string = process.cwd()): void {
  const gitignorePath = path.join(cwd, '.gitignore');
  const entry = '.aiui/tokens.json';

  if (fs.existsSync(gitignorePath)) {
    const content = fs.readFileSync(gitignorePath, 'utf-8');
    if (content.includes(entry)) return;
    fs.appendFileSync(gitignorePath, `\n# AIUI generated tokens\n${entry}\n`);
  }
}
