import type { MergedTokenMap, TokenValue } from '../types';

export interface CSSExportOptions {
  stylePackSlug?: string;
  includeRoot?: boolean;
  includeScoped?: boolean;
}

export interface CSSExportResult {
  content: string;
  filename: string;
}

/**
 * Convert a dot-notation token path to a CSS variable name.
 * "color.primary" -> "--color-primary"
 * "color.primary.hover" -> "--color-primary-hover"
 */
export function tokenPathToVariable(path: string): string {
  return '--' + path.replace(/\./g, '-');
}

interface GroupedTokens {
  colors: Array<{ variable: string; value: string }>;
  radius: Array<{ variable: string; value: string }>;
  fonts: Array<{ variable: string; value: string }>;
  spacing: Array<{ variable: string; value: string }>;
  shadows: Array<{ variable: string; value: string }>;
  other: Array<{ variable: string; value: string }>;
}

function categorize(key: string): keyof GroupedTokens {
  if (key.startsWith('color.')) return 'colors';
  if (key.startsWith('radius.')) return 'radius';
  if (key.startsWith('font.')) return 'fonts';
  if (key.startsWith('spacing.')) return 'spacing';
  if (key.startsWith('shadow.')) return 'shadows';
  return 'other';
}

function formatValue(value: TokenValue): string {
  const str = String(value);
  // Quote font names that contain spaces
  if (str.includes(' ') && !str.startsWith('"') && !str.startsWith("'") && !str.includes('(')) {
    return `"${str}"`;
  }
  return str;
}

/**
 * Group tokens by type for CSS output.
 */
export function groupTokensByType(tokens: MergedTokenMap): GroupedTokens {
  const groups: GroupedTokens = {
    colors: [],
    radius: [],
    fonts: [],
    spacing: [],
    shadows: [],
    other: [],
  };

  for (const [key, value] of Object.entries(tokens)) {
    const category = categorize(key);
    groups[category].push({
      variable: tokenPathToVariable(key),
      value: formatValue(value),
    });
  }

  // Sort within each group
  for (const group of Object.values(groups)) {
    group.sort((a: { variable: string; value: string }, b: { variable: string; value: string }) =>
      a.variable.localeCompare(b.variable)
    );
  }

  return groups;
}

const SECTION_LABELS: Record<keyof GroupedTokens, string> = {
  colors: 'Colors',
  radius: 'Border Radius',
  fonts: 'Typography',
  spacing: 'Spacing',
  shadows: 'Shadows',
  other: 'Other',
};

function renderVariableBlock(groups: GroupedTokens, selector: string): string {
  const sections: string[] = [];

  for (const [groupKey, label] of Object.entries(SECTION_LABELS)) {
    const entries = groups[groupKey as keyof GroupedTokens];
    if (entries.length === 0) continue;

    const vars = entries.map((e) => `  ${e.variable}: ${e.value};`).join('\n');
    sections.push(`  /* ${label} */\n${vars}`);
  }

  if (sections.length === 0) return '';
  return `${selector} {\n${sections.join('\n\n')}\n}`;
}

/**
 * Export merged tokens as CSS custom properties.
 */
export function exportCSSVariables(
  tokens: MergedTokenMap,
  options: CSSExportOptions = {}
): CSSExportResult {
  const { stylePackSlug, includeRoot = true, includeScoped = true } = options;

  const groups = groupTokensByType(tokens);
  const blocks: string[] = [];

  blocks.push('/* Auto-generated by AIUI — do not edit manually */');

  if (includeRoot) {
    const rootBlock = renderVariableBlock(groups, ':root');
    if (rootBlock) blocks.push(rootBlock);
  }

  if (includeScoped && stylePackSlug) {
    const scopedBlock = renderVariableBlock(groups, `.theme-${stylePackSlug}`);
    if (scopedBlock) blocks.push(scopedBlock);
  }

  const content = blocks.join('\n\n') + '\n';
  const filename = stylePackSlug ? `${stylePackSlug}-tokens.css` : 'design-tokens.css';

  return { content, filename };
}
