import type { MergedTokenMap, TokenValue } from '../types';

export interface TailwindExportResult {
  content: string;
  filename: string;
}

function extractByPrefix(tokens: MergedTokenMap, prefix: string): Record<string, TokenValue> {
  const result: Record<string, TokenValue> = {};
  for (const [key, value] of Object.entries(tokens)) {
    if (key.startsWith(prefix + '.')) {
      const name = key.slice(prefix.length + 1);
      result[name] = value;
    }
  }
  return result;
}

function mapColors(tokens: MergedTokenMap): Record<string, string> {
  const colors = extractByPrefix(tokens, 'color');
  const mapped: Record<string, string> = {};
  for (const [name] of Object.entries(colors)) {
    mapped[name] = `var(--color-${name})`;
  }
  return mapped;
}

function mapBorderRadius(tokens: MergedTokenMap): Record<string, string> {
  const radii = extractByPrefix(tokens, 'radius');
  const mapped: Record<string, string> = {};
  for (const [name, value] of Object.entries(radii)) {
    mapped[name] = String(value);
  }
  return mapped;
}

function mapFontFamily(tokens: MergedTokenMap): Record<string, string[]> {
  const fonts = extractByPrefix(tokens, 'font');
  const mapped: Record<string, string[]> = {};
  for (const [name, value] of Object.entries(fonts)) {
    mapped[name] = [String(value), 'sans-serif'];
  }
  return mapped;
}

function mapSpacing(tokens: MergedTokenMap): Record<string, string> {
  const spacing = extractByPrefix(tokens, 'spacing');
  const mapped: Record<string, string> = {};
  for (const [name, value] of Object.entries(spacing)) {
    mapped[name] = String(value);
  }
  return mapped;
}

function mapBoxShadow(tokens: MergedTokenMap): Record<string, string> {
  const shadows = extractByPrefix(tokens, 'shadow');
  const mapped: Record<string, string> = {};
  for (const [name, value] of Object.entries(shadows)) {
    mapped[name] = String(value);
  }
  return mapped;
}

function formatObject(obj: Record<string, unknown>, indent: number): string {
  const pad = ' '.repeat(indent);
  const innerPad = ' '.repeat(indent + 2);
  const entries = Object.entries(obj);
  if (entries.length === 0) return '{}';

  const lines = entries.map(([key, value]) => {
    if (Array.isArray(value)) {
      const items = value.map((v) => `'${v}'`).join(', ');
      return `${innerPad}'${key}': [${items}],`;
    }
    return `${innerPad}'${key}': '${value}',`;
  });

  return `{\n${lines.join('\n')}\n${pad}}`;
}

/**
 * Export merged tokens as a Tailwind CSS configuration partial.
 */
export function exportTailwindConfig(tokens: MergedTokenMap): TailwindExportResult {
  const colors = mapColors(tokens);
  const borderRadius = mapBorderRadius(tokens);
  const fontFamily = mapFontFamily(tokens);
  const spacing = mapSpacing(tokens);
  const boxShadow = mapBoxShadow(tokens);

  const content = `// Auto-generated by AIUI — do not edit manually
import type { Config } from 'tailwindcss';

const config: Partial<Config> = {
  theme: {
    extend: {
      colors: ${formatObject(colors, 6)},
      borderRadius: ${formatObject(borderRadius, 6)},
      fontFamily: ${formatObject(fontFamily, 6)},
      spacing: ${formatObject(spacing, 6)},
      boxShadow: ${formatObject(boxShadow, 6)},
    },
  },
};

export default config;
`;

  return { content, filename: 'tailwind.config.ts' };
}
