import type { Metadata } from 'next';
import { LandingNav } from '@/components/landing/LandingNav';
import { Footer } from '@/components/landing/Footer';

export const metadata: Metadata = {
  title: 'Privacy — AIUI',
  description: 'How AIUI handles your data, tokens, and design memory.',
};

export default function PrivacyPage() {
  return (
    <main className="editorial">
      <LandingNav />
      <article className="mx-auto max-w-[760px] px-6 lg:px-10 py-20 lg:py-28">
        <p className="eyebrow" style={{ fontSize: '0.6875rem', color: 'var(--ink-muted)' }}>
          Legal
        </p>
        <h1
          className="mt-4 text-[2.75rem] lg:text-[3.5rem] leading-[1.05]"
          style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}
        >
          Privacy.
        </h1>
        <p className="mt-3 text-[0.875rem]" style={{ color: 'var(--ink-muted)' }}>
          Last updated: April 26, 2026
        </p>

        <Section title="What we store">
          <p>
            AIUI stores the design data you create — projects, design tokens, and design profiles —
            along with the email address you signed up with. Nothing else is collected.
          </p>
        </Section>

        <Section title="What we do not store">
          <p>
            We do not store the contents of UI files generated by your AI tools. The MCP server
            sends your tokens and rules to the model; what the model writes back lives only in your
            local repository.
          </p>
        </Section>

        <Section title="Authentication">
          <p>
            Passwords are hashed with bcrypt. Sessions are signed JWTs delivered as HttpOnly
            cookies. If you sign in with Google, we receive your email, name, and avatar — never
            your Google password.
          </p>
        </Section>

        <Section title="Self-hosting">
          <p>
            If you self-host AIUI, none of the above applies — your data lives on your
            infrastructure and never reaches us.
          </p>
        </Section>

        <Section title="Contact">
          <p>
            Questions? Email{' '}
            <a
              href="mailto:hello@aiui.store"
              style={{ color: 'var(--accent)', textDecoration: 'underline' }}
            >
              hello@aiui.store
            </a>
            .
          </p>
        </Section>
      </article>
      <Footer />
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-12">
      <h2
        className="text-[1.25rem]"
        style={{ fontFamily: 'var(--font-display)', color: 'var(--ink)' }}
      >
        {title}
      </h2>
      <div className="mt-3 text-[0.9375rem]" style={{ color: 'var(--ink-soft)', lineHeight: 1.7 }}>
        {children}
      </div>
    </section>
  );
}
