import { describe, it, expect } from 'vitest';
import { transformTokens, inferFormat } from '../lib/transformer';

function makeTokens() {
  return [
    { key: 'color-primary', type: 'color', value: '#3b82f6' },
    { key: 'color-secondary', type: 'color', value: '#6366f1' },
    { key: 'font-body', type: 'font', value: 'Inter, sans-serif' },
    { key: 'spacing-sm', type: 'spacing', value: '0.5rem' },
    { key: 'radius-md', type: 'radius', value: '0.375rem' },
    { key: 'shadow-sm', type: 'shadow', value: '0 1px 2px rgba(0,0,0,0.05)' },
  ];
}

describe('inferFormat', () => {
  it('returns tailwind for nextjs with Tailwind', () => {
    expect(inferFormat('nextjs', true)).toBe('tailwind');
  });

  it('returns tailwind for vite with Tailwind', () => {
    expect(inferFormat('vite', true)).toBe('tailwind');
  });

  it('returns css for nextjs without Tailwind', () => {
    expect(inferFormat('nextjs', false)).toBe('css');
  });

  it('returns css for react without Tailwind', () => {
    expect(inferFormat('react', false)).toBe('css');
  });

  it('returns json for unknown without Tailwind', () => {
    expect(inferFormat('unknown', false)).toBe('json');
  });
});

describe('transformTokens — tailwind format', () => {
  it('returns content containing colors', () => {
    const result = transformTokens(makeTokens(), 'tailwind');
    expect(result.content).toContain('colors');
  });

  it('returns content containing fontFamily', () => {
    const result = transformTokens(makeTokens(), 'tailwind');
    expect(result.content).toContain('fontFamily');
  });

  it('returns content containing the primary color value', () => {
    const result = transformTokens(makeTokens(), 'tailwind');
    expect(result.content).toContain('#3b82f6');
  });

  it('returns filename aiui.tailwind.config.ts', () => {
    const result = transformTokens(makeTokens(), 'tailwind');
    expect(result.filename).toBe('aiui.tailwind.config.ts');
  });

  it('content starts with a generated comment', () => {
    const result = transformTokens(makeTokens(), 'tailwind');
    expect(result.content.startsWith('// Generated by AIUI CLI')).toBe(true);
  });
});

describe('transformTokens — css format', () => {
  it('returns content with :root {', () => {
    const result = transformTokens(makeTokens(), 'css');
    expect(result.content).toContain(':root {');
  });

  it('includes --color-primary: #3b82f6', () => {
    const result = transformTokens(makeTokens(), 'css');
    expect(result.content).toContain('--color-primary: #3b82f6');
  });

  it('returns filename aiui.tokens.css', () => {
    const result = transformTokens(makeTokens(), 'css');
    expect(result.filename).toBe('aiui.tokens.css');
  });
});

describe('transformTokens — json format', () => {
  it('parses as valid JSON', () => {
    const result = transformTokens(makeTokens(), 'json');
    expect(() => JSON.parse(result.content)).not.toThrow();
  });

  it('has all token keys', () => {
    const result = transformTokens(makeTokens(), 'json');
    const parsed = JSON.parse(result.content);
    const tokens = makeTokens();
    for (const token of tokens) {
      expect(parsed).toHaveProperty(token.key);
    }
  });

  it('each entry has value and type', () => {
    const result = transformTokens(makeTokens(), 'json');
    const parsed = JSON.parse(result.content);
    for (const key of Object.keys(parsed)) {
      expect(parsed[key]).toHaveProperty('value');
      expect(parsed[key]).toHaveProperty('type');
    }
  });

  it('returns filename tokens.json', () => {
    const result = transformTokens(makeTokens(), 'json');
    expect(result.filename).toBe('tokens.json');
  });
});

describe('transformTokens — edge cases', () => {
  it('handles empty array for tailwind format', () => {
    const result = transformTokens([], 'tailwind');
    expect(typeof result.content).toBe('string');
    expect(result.content.length).toBeGreaterThan(0);
  });

  it('handles empty array for css format', () => {
    const result = transformTokens([], 'css');
    expect(result.content).toContain(':root {');
  });

  it('handles empty array for json format', () => {
    const result = transformTokens([], 'json');
    const parsed = JSON.parse(result.content);
    expect(Object.keys(parsed)).toHaveLength(0);
  });

  it('handles a single token', () => {
    const single = [{ key: 'color-brand', type: 'color', value: '#ff0000' }];
    const result = transformTokens(single, 'tailwind');
    expect(result.content).toContain('#ff0000');
  });
});
